Adjust deploys so they work for springdale (ppa qa as test case)
Princeton-CDH/CDH_ansible pull request #55
Opened 2020-12-17 16:51 UTC by rlskoeser

When I tried to deploy ppa to qa I ran into a number of problems related to our recent changes for the new pul/ubuntu deploys.

Here are the fixes I needed to get it working again. I haven't tested a pul deploy with this changes, and probably should before merging.

We probably should add the same changes (in terms of the variables I had to add and change for ppa) to the other projects that we might need to deploy (mep, derrida).

2020-12-21 17:01 UTC, thatbudakguy approved these changes
looks good! this made me idly wonder if we will end up having roles that repeat an idiom of:
- put all the tasks in a top-level block, like we do to use `rescue`
- make the top-level block use `become`
- make the top-level block use `become_user`
- have the `become_user` value be a parameter with a default

...so that it's easy to change at a high level which user a role is running as.

2020-12-21 22:26 UTC, rlskoeser commented on roles/build_virtualenv/tasks/main.yml
> +    #   when:  ansible_distribution == 'Springdale'
I don't trust that we don't need it for sure until we've run this in production, since libservdhc7 doesn't match production exactly.

2021-01-04 13:24 UTC, thatbudakguy approved these changes

2021-01-04 16:27 UTC, thatbudakguy requested changes
Just tested a PUL deploy (cdh-web QA) and the `build_dependencies` step breaks because we're trying to install packages as `deploy_user` (instead of root, I guess).

It seems weird that we're using the `apt` module to do this for Springdale - isn't the package manager `yum`? It looks like there's a [different ansible builtin for that](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html). It also seems weird that it works as `deploy_user`; afaik you always need to `sudo` to install/update packages.

2021-01-12 21:30 UTC, rlskoeser commented
> Just tested a PUL deploy (cdh-web QA) and the `build_dependencies` step breaks because we're trying to install packages as `deploy_user` (instead of root, I guess).
> 
> It seems weird that we're using the `apt` module to do this for Springdale - isn't the package manager `yum`? It looks like there's a [different ansible builtin for that](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html). It also seems weird that it works as `deploy_user`; afaik you always need to `sudo` to install/update packages.

Good catch! Apt doesn't work on Springdale and we don't have permission to install packages anyway, that's handled external to the ansible scripts. Not sure what I was thinking... 

I think maybe I wasn't expecting this to get run on Springdale at all based on the dependencies... but it's been a while since I worked on it and I forget!

I'm not sure what the tmux config used to look like for Springdale, but it doesn't seem like a big deal if we lose it.

2021-01-15 16:41 UTC, thatbudakguy approved these changes

2021-01-15 16:53 UTC, merged